# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Create version number
      id: version
      run: echo "v=$(date +'%Y.%m%d.${{github.run_number}}')" >> $GITHUB_OUTPUT
    - name: Publish linux-arm
      run: dotnet publish EliteSx2Mqtt/EliteSx2Mqtt.csproj -r linux-arm --self-contained true -p:PublishSingleFile=true -p:Version=${{steps.version.outputs.v}} -c Release -o ${{env.DOTNET_ROOT}}/linux-arm
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: linux-arm-${{steps.version.outputs.v}}
        path: ${{env.DOTNET_ROOT}}/linux-arm

    - name: Publish linux-x64
      run: dotnet publish EliteSx2Mqtt/EliteSx2Mqtt.csproj -r linux-x64 --self-contained true -p:PublishSingleFile=true -p:Version=${{steps.version.outputs.v}} -c Release -o ${{env.DOTNET_ROOT}}/linux-x64
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: linux-x64-${{steps.version.outputs.v}}
        path: ${{env.DOTNET_ROOT}}/linux-x64
